# ThePit Plugin Configuration

server-ip: "play.example.com"

player-spawn:
  x: 0.5
  y: 100
  z: 0.5
  yaw: 90
  pitch: 0
  world: "world_elements"

#Ranks
Ranks:
  owner:
    prefix: "&4[Owner] "
    color: "&4"
    permission: "pit.rank.owner"

  admin:
    prefix: "&c[Admin] "
    color: "&c"
    permission: "pit.rank.admin"

  default:
    prefix: "&7"
    color: "&7"
    permission: "pit.rank.default"

mystic-drop-chance: 0.01 # 1% chance to drop a mystic.

#Bot Data
bot-skins:
  - "Notch"
  - "Steve"
  - "Alex"
  - "NotPixels"

bot-spawn:
  x: 0.5
  y: 85
  z: 0.5
  yaw: 180
  pitch: 0
  world: "world_elements"