name: ThePit
version: 1.0
main: com.thepit.Main
description: A Minecraft plugin for ThePit
author: YourName

commands:
  perks:
    description: Opens the perks menu
  setgold:
    description: Set a player's gold amount
    usage: /setgold <player> <amount>
    permission: thepit.setgold
  setxp:
    description: Set a player's XP
    usage: /setxp <player> <amount>
    permission: thepit.setxp
  pitench:
    description: Add an enchantment
    usage: /pitench <enchantment> <level>
    permission: thepit.pitench
  prestige:
    description: Prestige once you reach level 120
    usage: /prestige
    permission: myplugin.prestige
  setenchant:
    description: Set an enchant on an item
    usage: /setenchant <player> <enchant> <level>
    permission: thepit.setenchant
  addlives:
    description: Add lives to the held item
    usage: /addlives <lives> <maxLives>
    permission: pit.addlives
  setunbreakable:
    description: Set the held item to be unbreakable
    usage: /setunbreakable
    permission: pit.unbreakable



permissions:
  thepit.setgold:
    description: Allows setting gold
    default: op

  thepit.setxp:
    description: Allows setting XP
    default: op

  thepit.pitench:
    description: Allows adding enchantments
    default: op

  thepit.prestige:
    description: Allows the player to prestige
    default: op

  thepit.setenchant:
    description: Allows setting enchantments on items
    default: op
  thepit.addlives:
    description: Allows adding lives to items
    default: op
  thepit.unbreakable:
    description: Allows making items unbreakable
    default: op
  thepit.rank.owner:
      description: "Owner rank"
      default: op
  thepit.rank.admin:
    description: "Admin rank"
    default: false
  thepit.rank.default:
    description: "Default rank"
    default: true



