name: ThePit
version: 1.0
main: com.thepit.Main
description: A Minecraft plugin for ThePit
author: YourName

commands:
  perks:
    description: Opens the perks menu
  setgold:
    description: Set a player's gold amount
    usage: /setgold <player> <amount>
    permission: thepit.setgold
  setxp:
    description: Set a player's XP
    usage: /setxp <player> <amount>
    permission: thepit.setxp
  pitench:
    description: Add an enchantment
    usage: /pitench <enchantment> <level>
    permission: thepit.pitench
  prestige:
    description: Prestige once you reach level 120
    usage: /prestige
    permission: myplugin.prestige



permissions:
  thepit.setgold:
    description: Allows setting gold
    default: op

  thepit.setxp:
    description: Allows setting XP
    default: op

  thepit.pitench:
    description: Allows adding enchantments
    default: op

  thepit.prestige:
    description: Allows the player to prestige
    default: op


